nome = input("Digite seu nome: ")
cpf = input("Digite seu cpf: ")
uf = input("Digite sua unidade federativa: ")

print("-" * 40)
print("Confirmação de cadastro:")
print("Nome:", nome)
print("CPF:", cpf)
print("UF:", uf)
print("-" * 40)
